version: "3.4"
services:
  mySwoft:
    image: swoft/swoft
    ports:
     - "18306:18306"
     - "18307:18307"
     - "18308:18308"
    depends_on:
      - redis
      - mysql
      - mongo
    volumes:
      - "./:/var/www/swoft"
    # command: php -S 0.0.0.0:80


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "//d/WWW/docker/tmp/redis:/mydata"
  

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"
    volumes:
      - "//d/WWW/docker/tmp/mysql:/mydata"


  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "//d/WWW/docker/tmp/mongo:/mydata"

    
